# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: ..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\UC33e\config.py
# Bytecode version: 3.11a7e (3495)
# Source timestamp: 2025-03-17 14:05:58 UTC (1742220358)

from .consts import *
pass
TRANSPORT_CONTROLS = {'STOP': GENERIC_STOP, 'PLAY': GENERIC_PLAY, 'REC': GENERIC_REC, 'LOOP': GENERIC_LOOP, 'RWD': GENERIC_RWD, 'FFWD': GENERIC_FFWD}
pass
DEVICE_CONTROLS = ((GENERIC_ENC1, 0), (GENERIC_ENC2, 1), (GENERIC_ENC3, 2), (GENERIC_ENC4, 3), (GENERIC_ENC5, 4), (GENERIC_ENC6, 5), (GENERIC_ENC7, 6), (GENERIC_ENC8, 7))
pass
VOLUME_CONTROLS = ((GENERIC_SLI1, 0), (GENERIC_SLI2, 1), (GENERIC_SLI3, 2), (GENERIC_SLI4, 3), (GENERIC_SLI5, 4), (GENERIC_SLI6, 5), (GENERIC_SLI7, 6), (GENERIC_SLI8, 7))
pass
TRACKARM_CONTROLS = (GENERIC_BUT1, GENERIC_BUT2, GENERIC_BUT3, GENERIC_BUT4, GENERIC_BUT5, GENERIC_BUT6, GENERIC_BUT7, GENERIC_BUT8)
pass
BANK_CONTROLS = {'TOGGLELOCK': GENERIC_BUT9, 'BANKDIAL': -1, 'NEXTBANK': GENERIC_PAD5, 'PREVBANK': GENERIC_PAD1, 'BANK1': -1, 'BANK2': -1, 'BANK3': -1, 'BANK4': -1, 'BANK5': -1, 'BANK6': -1, 'BANK7': -1, 'BANK8': -1}
pass
CONTROLLER_DESCRIPTIONS = {'INPUTPORT': 'UC-33 USB MIDI Controller (Port 1)', 'OUTPUTPORT': 'UC-33 USB MIDI Controller (Port 1)', 'CHANNEL': 0}
pass
MIXER_OPTIONS = {'NUMSENDS': 2, 'SEND1': (-1, -1, -1, -1, -1, -1, -1, -1), 'SEND2': (-1, -1, -1, -1, -1, -1, -1, -1), 'MASTERVOLUME': 28}