# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: ..\..\..\output\Live\win_64_static\Release\python-bundle\MIDI Remote Scripts\BCF2000\config.py
# Bytecode version: 3.11a7e (3495)
# Source timestamp: 2025-03-17 14:05:58 UTC (1742220358)

from .consts import *
pass
TRANSPORT_CONTROLS = {'STOP': GENERIC_STOP, 'PLAY': GENERIC_PLAY, 'REC': GENERIC_REC, 'LOOP': GENERIC_LOOP, 'RWD': GENERIC_RWD, 'FFWD': GENERIC_FFWD}
pass
DEVICE_CONTROLS = ((GENERIC_ENC1, 0), (GENERIC_ENC2, 0), (GENERIC_ENC3, 0), (GENERIC_ENC4, 0), (GENERIC_ENC5, 0), (GENERIC_ENC6, 0), (GENERIC_ENC7, 0), (GENERIC_ENC8, 0))
pass
VOLUME_CONTROLS = ((GENERIC_SLI1, -1), (GENERIC_SLI2, -1), (GENERIC_SLI3, -1), (GENERIC_SLI4, -1), (GENERIC_SLI5, -1), (GENERIC_SLI6, -1), (GENERIC_SLI7, -1), (GENERIC_SLI8, -1))
pass
TRACKARM_CONTROLS = (GENERIC_BUT1, GENERIC_BUT2, GENERIC_BUT3, GENERIC_BUT4, GENERIC_BUT5, GENERIC_BUT6, GENERIC_BUT7, GENERIC_BUT8)
pass
BANK_CONTROLS = {'TOGGLELOCK': GENERIC_BUT9, 'BANKDIAL': -1, 'NEXTBANK': GENERIC_PAD5, 'PREVBANK': GENERIC_PAD1, 'BANK1': 65, 'BANK2': 66, 'BANK3': 67, 'BANK4': 68, 'BANK5': 69, 'BANK6': 70, 'BANK7': 71, 'BANK8': 72}
pass
CONTROLLER_DESCRIPTIONS = {'INPUTPORT': 'BCF2000', 'OUTPUTPORT': 'BCF2000', 'CHANNEL': 0}
pass
MIXER_OPTIONS = {'NUMSENDS': 2, 'SEND1': (-1, -1, -1, -1, -1, -1, -1, -1), 'SEND2': (-1, -1, -1, -1, -1, -1, -1, -1), 'MASTERVOLUME': -1}